default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: url_shortner_dev
  username: spp_user
  password: admin

production:
  <<: *default
  database: url_shortner_production
  username: spp_user
  password: admin

test: &test
  <<: *default
  database: url_shortner_test
  username: spp_user
  password: admin

cucumber:
  <<: *test